
	<div id="banner" class="hidden-xs">
		<div class="container">
			<div class="row">
				<div class="headerimage">
					<div class="col-sm-7 col-md-6 col-md-push-1 col-lg-push-2">
						<h2>Vidya dadati vinayam Vinayad yati patratam | <br />
						Patratvaddhanamapnoti Dhanaddharmam tatah sukham ||</h2>
						<br />
						<h1>Knowledge gives humility, from humility, one attains character.
						From character, one acquires wealth,<br />from wealth good deeds (righteousness) follow and<br />then happiness.</h1>
					</div>
					<div class="col-sm-4 col-sm-push-1 col-lg-push-2">
						<img src="images/saraswati04.png" width="200" height="250" />
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="container">	
		<section id="announcement">
			<div class="row">	
				<div class="col-xs-12">
					<!-- <h3>ANNOUNCEMENT: Registration for new students will be on 10th September from 12:30 - 14:00</h3> -->

				</div>	
			</div>	
		</section>
	</div>
	