
	<footer>
		<div class="container text-center">        
			<div class="row">
				<div class="col-xs-12">
					<img src="images/logo_footer.png" />
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12">			
					<ul>
						<li><a href="index.php">Home</a></li>
						<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">About Us<span class="caret"</span></a>
							<ul class="dropdown-menu">
								<li><a href="history.php">History</a></li>
								<li><a href="objectives.php">Objectives</a></li>
								<li><a href="committee.php">Committee Members</a></li>
								<li><a href="volunteers.php">Volunteers</a></li>  							
							</ul>
						</li>
						<li><a href="events.php">Events</a></li>				
						<li><a href="keydates.php">Key Dates</a></li>				
						<li><a href="contactus.php">Contact Us</a></li>
					</ul>			
				</div>
			</div>					
			<div class="row">
				<div class="col-xs-12">								
					<p class="copyright">Copyright &copy; <?php echo date('Y'); ?>  Hindu Youth Association. All rights reserved. Registered charity no. 1142405</p>
				</div>
			</div>
		</div><!-- end Container-->      			
	</footer>
	<script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>