
	<header>
		<div class="container">
			<div class="row">	
				<div class="col-xs-12 col-sm-3 col-sm-push-0 col-lg-3 col-lg-push-1 text-center">
					<a href="index.php"><img src="images/logo_header.png" width="232" /></a>				
				</div>								
				<div class="col-xs-12 col-sm-7 col-lg-7">
					<p class="headerquote"><img src="images/quote_mark.png" />Education is not the amount of information that is put into your brain and runs riot there, undigested all your life. We must have life‑building, man‑making, character‑making, assimilation of ideas.</p>
					<p class="headerquote name">Swami Vivekananda</p>
				</div>
				<div class="col-sm-2 hidden-xs">					
					<img class="headerimage" src="images/swami_vivekananda.png" height="180"/>					
				</div>

				<div class="visible-xs">	
					<div class="col col-xs-12">
						<div id="socialmedia" style="width:100%;text-align:center;margin-top:20px;">
							<p style="color:#cf771b">Stay Connected</p>
							<a href="https://www.facebook.com/Hindu-Youth-Association-110274709136894/" target="_blank">
								<img src="../images/fb.png" alt="Follow Us" width="200" />
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>		
	</header>

