  <!-- Navbar -->
  	<nav class="navbar navbar-inverse navbar-fixed-top hidden-lg">
  		<div class="container-fluid">
  			<div class="navbar-header">
  				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynavbar">
  					<span class="icon-bar"></span>
  					<span class="icon-bar"></span>
  					<span class="icon-bar"></span>
  				</button>			
  				<a href="index.php" class="navbar-brand"><span class="glyphicon glyphicon-home"></span></a>
  			</div>
  			<div class="collapse navbar-collapse" id="mynavbar">
  				<ul class="nav navbar-nav">
  					<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">ABOUT HYA<span class="caret"></span></a>
  						<ul class="dropdown-menu">
  							<li><a href="history.php">History</a></li>
  							<li><a href="objectives.php">Objectives</a></li>
  							<li><a href="committee.php">Committee Members</a></li>
  							<li><a href="volunteers.php">Volunteers</a></li>  							
  						</ul>
  					</li>
  					<li><a href="events.php">EVENTS</a></li>  					
  					<li><a href="keydates.php">KEY DATES</a></li>
  					<li><a href="contactus.php">CONTACT US</a></li>
  				</ul>
  			</div>
  		</div><!-- End Container-->
  	</nav><!-- End navbar -->

	<nav class="visible-lg">
		<div class="navcontent">	
			<ul>
				<a href="index.php"><li class="home">HOME<div class="sub">Hindu Youth Association</div></li></a>
					<li class="about">ABOUT HYA<div class="sub">Our aims and history</div>
						<ul class="subnav">
							<a href="history.php"><li>History</li></a>
							<a href="objectives.php"><li>Objectives</li></a>
							<a href="committee.php"><li>Committee Members</li></a>
							<a href="volunteers.php"><li>Volunteers</li></a>
						</ul>
					</li>
				<a href="events.php"><li>EVENTS<div class="sub">Events and Activities</div></li></a>
				<a href="keydates.php"><li>KEY DATES<div class="sub">2016-2017</div></li></a>				
				<a href="contactus.php"><li class="last">CONTACT US<div class="sub">Get in touch</div></li></a>
			</ul>
		</div>
	</nav>