
	<div class="col-sm-3 hidden-xs""> 			
		<div id="sidebar">
			<h1 class="first">Stay Connected</h1>
			<div id="socialmedia">
				<a href="https://www.facebook.com/Hindu-Youth-Association-110274709136894/" target="_blank">
					<img src="../images/fb.png" alt="Follow Us" width="200" />
				</a>
			</div>

			<h1>Upcoming Events</h1>

			<h1>Useful Links</h1>
			<ul>
				<li><a href="http://www.balagokulam.org/" target="_blank">Baal Gokulam</a> - Kids</li>
				<li><a href="http://www.bbc.co.uk/bitesize/" target="_blank">BBC Bite Size</a> - KS1 to A Levels</li>
				<li><a href="http://www.bbc.co.uk/education/" target="_blank">BBC Education</a> - KS1 to GCSE</li>
				<li><a href="http://www.learninggamesforkids.com/" target="_blank">Educational Games</a> - Pre-school</li>		
				<li><a href="http://www.hinduacademy.org/" target="_blank">Hindu Academy</a> - All Levels</li>
				<li><a href="http://www.britishcouncil.org/learn-english/" target="_blank">Learn English</a> - All Levels</li>
				<li><a href="http://www.maths-games.org/" target="_blank">Maths Learning Games</a> - KS1 to KS3</li>
			</ul>
		</div>
	</div>
